### ISSUE TITLE
Can't see last 2 recovery keys in iPhone 5S 

### ISSUE THREAD

**Issue by allenyllee** [blockfirm/bithodl-app#1]
Can't see last 2 recovery keys in iPhone 5S 

### How to reproduce
1. Open app in iPhone 5S
2. Click on Create A New Wallet

### Actual behavior
The last 2 recovery keys was covered by the button "I HAVE SAVED THESE WORDS" and can't be seen.

### Expected behavior
It Should see all 12 recovery keys no matter what screen resolution is.

### Context/Environment
iPhone 5S iOS 11.2.2

### Possible fixes
Making the app's fonts/column/images size to adapt to the small screen resolution

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/blockfirm/bithodl-app/1/c240cf46-60db-4e53-b957-91ef15bd4a78/4e47f735-6945-4c6a-8ce5-cbc968edad5a) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by timothyej** [comment]
Thank you for the bug report! I will look into this as soon as possible 👍

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by timothyej** [comment]
This issue has been fixed in the latest release of BitHodl, version 1.1.0. Please note that it can take some time before the update is available on the App Store.

Thank you for contributing to BitHodl. Let me know if you have any other issues or questions.
